### ISSUE TITLE
Hey, I am trying to run the code in google colab and getting few errors, here is the link  https://colab.research.google.com/drive/1phQEBbSC-tuUmW4DqtwbgmfWCEeT_39_

### ISSUE THREAD

**Issue by TonyStark09** [kwonmha/Bidirectional-LSTM-with-attention-for-relation-classification#2]

**Comment by kwonmha** [comment]
The error message says tensorflow variable 'word_embedding' cannot be created twice under the same name.
That means, BiLSTMAttention is initiated more than once though you created the class instance once.

I can't figure out why the initiating codes are executed twice or more.
You'd better check how the BiLSTMAttention class is created twice.

If you can't find the cause, add 
`with tf.variable_scope("Any_Name_Like_BiLSTMAttention", reuse=True):`
just above `self.W_emb = tf.get_variable("word_embeddings", [vocab_size, embedding_size])`.
